cores: 8
format: new
samplegroup: yes
tolerance_MS1: 0
ppm_MS1: 15
adducts_pos:
- '[M+H]+'
- '[M+Na]+'
adducts_neg: '[M-H]-'
tolerance_MS2: 0
ppm_MS2: 15
dp_tresh: 0.0
int_tresh: 5
toleranceRt_MS1: 30
toleranceRt_MS2: 30
ion_mode_match: yes
output_dir: new_test_output
save_rds: yes
save_tsv: yes
MS1_lib_ext: new_test_library/MS1_external
MS1_lib_inhouse: new_test_library/MS1_inhouse
MS2_lib_pos: new_test_library/MS2_inhouse_pos
MS2_lib_neg: new_test_library/MS2_inhouse_neg
MS2_lib_pos_ext: new_test_library/MS2_external_pos
MS2_lib_neg_ext: new_test_library/MS2_external_neg
MS1_data_pos: new_test_input/output_slaw_pos/data_reduced_d88201d5aa202773e4893278bfdc0c40.csv
MS2_data_pos: new_test_input/output_slaw_pos/spectra_d88201d5aa202773e4893278bfdc0c40.mgf
studydesign_pos: new_test_input/output_slaw_pos/studydesign.csv
MS1_data_pos_full: new_test_input/output_slaw_pos/data_full_d88201d5aa202773e4893278bfdc0c40.csv
MS1_data_neg: new_test_input/output_slaw_neg/data_reduced_d74912ba588e4567383cb1dda27e1a9f.csv
MS2_data_neg: new_test_input/output_slaw_neg/spectra_d74912ba588e4567383cb1dda27e1a9f.mgf
studydesign_neg: new_test_input/output_slaw_neg/studydesign.csv
MS1_data_neg_full: new_test_input/output_slaw_pos/data_full_d88201d5aa202773e4893278bfdc0c40.csv
