cores: 8
format: new
rindex: no
rindex_time:
- 1.0
- 2.0
- 3.0
- 4.0
- 5.0
- 6.0
- 7.0
- 8.0
- 9.0
- 10.0
- 11.0
- 12.0
- 13.0
- 14.0
- 15.0
- 16.0
- 17.0
- 18.0
- 19.0
- 20.0
rindex_index:
- 100
- 200
- 300
- 400
- 500
- 600
- 700
- 800
- 900
- 1000
- 1100
- 1200
- 1300
- 1400
- 1500
- 1600
- 1700
- 1800
- 1900
- 2000
rindex_mz: []
samplegroup: no
tolerance_MS1: 0
ppm_MS1: 15
adducts_pos:
- '[M+H]+'
- '[M+Na]+'
adducts_neg: '[M-H]-'
tolerance_MS2: 0
ppm_MS2: 15
dp_tresh: 0.0
int_tresh: 5
toleranceRt_MS1: 30
toleranceRt_MS2: 30
ion_mode_match: yes
output_dir: Demo/new/test_output
save_rds: yes
save_tsv: yes
MS1_lib_pos: Demo/new/test_library/MS1_inhouse_pos
MS1_lib_neg: Demo/new/test_library/MS1_inhouse_neg
MS1_lib_pos_ext: Demo/new/test_library/MS1_external_pos
MS1_lib_neg_ext: Demo/new/test_library/MS1_external_pos
MS2_lib_pos: Demo/new/test_library/MS2_inhouse_pos
MS2_lib_neg: Demo/new/test_library/MS2_inhouse_neg
MS2_lib_pos_ext: Demo/new/test_library/MS2_external_pos
MS2_lib_neg_ext: Demo/new/test_library/MS2_external_neg
method_prefix: ''
MS1_data_pos: E:\01_MPC\ProjectData\Bio-Chemoinformatics\R\Projects\NTAnnotationWorkflow\Demo\new\test_input\output_slaw_pos\data_reduced_d88201d5aa202773e4893278bfdc0c40.csv
MS2_data_pos: E:\01_MPC\ProjectData\Bio-Chemoinformatics\R\Projects\NTAnnotationWorkflow\Demo\new\test_input\output_slaw_pos\spectra_d88201d5aa202773e4893278bfdc0c40.mgf
studydesign_pos: E:\01_MPC\ProjectData\Bio-Chemoinformatics\R\Projects\NTAnnotationWorkflow\Demo\new\test_input\output_slaw_pos\studydesign.csv
MS1_data_pos_full: E:\01_MPC\ProjectData\Bio-Chemoinformatics\R\Projects\NTAnnotationWorkflow\Demo\new\test_input\output_slaw_pos\data_full_d88201d5aa202773e4893278bfdc0c40.csv
MS1_data_neg: E:\01_MPC\ProjectData\Bio-Chemoinformatics\R\Projects\NTAnnotationWorkflow\Demo\new\test_input\output_slaw_neg\data_reduced_d74912ba588e4567383cb1dda27e1a9f.csv
MS2_data_neg: E:\01_MPC\ProjectData\Bio-Chemoinformatics\R\Projects\NTAnnotationWorkflow\Demo\new\test_input\output_slaw_neg\spectra_d74912ba588e4567383cb1dda27e1a9f.mgf
studydesign_neg: E:\01_MPC\ProjectData\Bio-Chemoinformatics\R\Projects\NTAnnotationWorkflow\Demo\new\test_input\output_slaw_neg\studydesign.csv
MS1_data_neg_full: E:\01_MPC\ProjectData\Bio-Chemoinformatics\R\Projects\NTAnnotationWorkflow\Demo\new\test_input\output_slaw_neg\data_full_d74912ba588e4567383cb1dda27e1a9f.csv
