cores: 1
MS1_data_pos: test_input/output_slaw_pos/datamatrices/annotated_peaktable_f94cff64cfc8564eef1c60f903c85471_reduced.csv
MS2_data_pos: test_input/output_slaw_pos/fused_mgf/fused_mgf_f94cff64cfc8564eef1c60f903c85471.mgf
MS1_data_neg: test_input/output_slaw_neg/datamatrices/annotated_peaktable_0b2770c3dd0cacbd7de7dec2930396f2_reduced.csv
MS2_data_neg: test_input/output_slaw_neg/fused_mgf/fused_mgf_0b2770c3dd0cacbd7de7dec2930396f2.mgf
samplegroup: yes
studydesign_pos: test_input/output_slaw_pos/studydesign.csv
studydesign_neg: test_input/output_slaw_neg/studydesign.csv
tolerance_MS1: 0
ppm_MS1: 15
adducts_pos:
- '[M+H]+'
- '[M+Na]+'
adducts_neg: '[M-H]-'
tolerance_MS2: 0
ppm_MS2: 15
dp_tresh: 0.0
int_tresh: 5
toleranceRt_MS1: 30
toleranceRt_MS2: 30
MS1_lib_ext: test_library/MS1_external
MS1_lib_inhouse: test_library/MS1_inhouse
MS2_lib_pos: test_library/MS2_inhouse_pos
MS2_lib_neg: test_library/MS2_inhouse_neg
MS2_lib_pos_ext: test_library/MS2_external_pos
MS2_lib_neg_ext: test_library/MS2_external_neg
ion_mode_match: yes
output_dir: test_output
save_rds: yes
save_tsv: yes
MS1_data_pos_full: test_input/output_slaw_pos/datamatrices/annotated_peaktable_f94cff64cfc8564eef1c60f903c85471_full.csv
MS1_data_neg_full: test_input/output_slaw_pos/datamatrices/annotated_peaktable_f94cff64cfc8564eef1c60f903c85471_full.csv
