# ==============================================================================
# general parameter
#
# General parameter settings such as number of cores
# ==============================================================================
cores: 8
format: "new" #select if old or new SLAW format is used

# ==============================================================================
# Retention indexing
#
# Parameters for retention indexing
# ==============================================================================
rindex: TRUE
rindex_time: [1.00,2.00,3.00,4.00,5.00,6.00,7.00,8.00,9.00,10.00,11.00,12.00,13.00,14.00,15.00,16.00,17.00,18.00,19.00,20.00]
rindex_index: [100,200,300,400,500,600,700,800,900,1000,1100,1200,1300,1400,1500,1600,1700,1800,1900,2000]
rindex_mz: []

# ==============================================================================
# Sample grouping
#
# Data of study design and sample grouping
# ==============================================================================
samplegroup:	FALSE

# ==============================================================================
# MS1 settings
#
# Settings used for MS1 and MS2 processing and annotation
# Adduct namings according to MetaboCoreUitls are used
# ==============================================================================
tolerance_MS1: 0 # absolute allowed tolerance
ppm_MS1: 15 # relative allowed tolerance
adducts_pos: ["[M+H]+","[M+Na]+"]
adducts_neg: ["[M-H]-"]

# ==============================================================================
# MS2 settings
#
# Settings specific to MS2 processing and annotation
# ==============================================================================
tolerance_MS2: 0 # absolute allowed tolerance
ppm_MS2:	15 # relative allowed tolerance
dp_tresh:	0.0 # Threshold for dot product score
int_tresh: 5 # Percentage of base peak intensity as threshold that will be removed from Spectra

# ==============================================================================
# chromatographic settings
#
# Settings for use of retention time and/or indexing
# ==============================================================================
toleranceRt_MS1: 30 # RT threshold used for annotation
toleranceRt_MS2: 30 # RT threshold used for annotation

# ==============================================================================
# Ion mode matching
#
# Shall matching between ion modes be performed?
# ==============================================================================
ion_mode_match: TRUE

# ==============================================================================
# data output
#
# Directory and type of output
# ==============================================================================
output_dir:	"test_output"
save_rds: TRUE
save_tsv: TRUE

# ==============================================================================
# Statistical and further analysis
#
# Directory and type of output
# ==============================================================================
#annotated_only:	TRUE # Shall the output only contain annotated Features? 
#plot_headtail: FALSE	# Shall head-tail plots be produced and stored in output directory?
#plot_boxplot:	FALSE	# Shall boxplots generated for annotated features?
#plot_pca: FALSE	#Shall pca and t-sne be generated for output? 
